baseURL = "https://tour.dgraph.io"
languageCode = "en-us"
title = "A Tour of Dgraph"
theme="hugo-tutorials"

[[menu.main]]
  name = "Introduction"
  url = "/intro/"
  identifier = "intro"
  weight = 1
[[menu.main]]
  name = "Basic GraphQL+- features"
  url = "/basic/"
  identifier = "basic"
  weight = 2
[[menu.main]]
  name = "Schema - describe your data"
  url = "/schema/"
  identifier = "schema"
  weight = 3
[[menu.main]]
  name = "Data, More Data"
  url = "/moredata/"
  identifier = "moredata"
  weight = 4
[[menu.main]]
  name = "Query Blocks, Query Variables and Aggregation"
  url = "/blocksvars/"
  identifier = "blocksvars"
  weight = 5
[[menu.main]]
    name = "Search - more ways to find nodes"
    url = "/search/"
    identifier = "search"
    weight = 6


[params]
  [params.menudesc]
    intro = "In this lesson you'll learn how to set up and run Dgraph for the tutorial and learn about graph databases."
    basic = "Here you'll learn the basics of how to query graph data from Dgraph and how to use and interpret the results."
    schema = "This lesson shows you how schemas work inside Dgraph, and how to add, update and delete data (in Dgraph, that's mutate data)."
    moredata = "Now that you've got some Dgraph experience, this lesson shows you how to use dgraph live loader to load large datasets.  You'll need this bigger dataset for the remaining sections of the tutorial."
    blocksvars = "This lesson shows you how to build more powerful queries with multiple query blocks and query variables."
    search = "In this lesson, you'll learn about Dgraph's search features."
