baseURL = "https://tour.dgraph.io"
languageCode = "en-us"
title = "A Tour of Dgraph"
theme = "hugo-tutorials"
canonifyURLs = true

[[menu.main]]
  name = "Introduction"
  url = "/intro/1/"
  identifier = "intro"
  weight = 1
[[menu.main]]
  name = "Basic Features"
  url = "/basic/1/"
  identifier = "basic"
  weight = 2
[[menu.main]]
  name = "Schema"
  url = "/schema/1/"
  identifier = "schema"
  weight = 3
[[menu.main]]
  name = "Data, More Data"
  url = "/moredata/1/"
  identifier = "moredata"
  weight = 4
[[menu.main]]
  name = "Query Blocks, & Variables"
  url = "/blocksvars/1/"
  identifier = "blocksvars"
  weight = 5
[[menu.main]]
    name = "Search"
    url = "/search/1/"
    identifier = "search"
    weight = 6

[[menu.bonus]]
    name = "Upsert Block"
    url = "/upsert/1/"
    identifier = "upsert"
    weight = 1
[[menu.bonus]]
    name = "Bulk Upsert"
    url = "/bulkupsert/1/"
    identifier = "bulk"
    weight = 2
[[menu.bonus]]
    name = "Upsert Migration"
    url = "/migration/1/"
    identifier = "Migration"
    weight = 3
[[menu.bonus]]
    name = "Upsert Migration"
    url = "/Migration/2/"
    identifier = "Migration1"
    weight = 4
    
[[menu.videos]]
    name = "videos"
    url = "/videos/1/"
    identifier = "videos"
    weight = 1
[[menu.videos]]
    name = "videos"
    url = "/videos/2/"
    identifier = "videos 2"
    weight = 2

[params]
  mainSections = ["main"] 
  [params.menudesc]
    intro = "In this lesson you'll learn how to set up and run Dgraph for the tutorial and learn about graph databases."
    basic = "Here you'll learn the basics of how to query graph data from Dgraph and how to use and interpret the results."
    schema = "This lesson shows you how schemas work inside Dgraph, and how to add, update and delete data (in Dgraph, that's mutate data)."
    moredata = "Now that you've got some Dgraph experience, this lesson shows you how to use dgraph live loader to load large datasets.  You'll need this bigger dataset for the remaining sections of the tutorial."
    blocksvars = "This lesson shows you how to build more powerful queries with multiple query blocks and query variables."
    search = "In this lesson, you'll learn about Dgraph's search features."

    upsert = "In this lesson, you'll learn about Dgraph's Upsert Block features."
    bulk = "In this lesson, you'll learn about Bulk upserts."
