baseURL = "https://dgraph.io/tour/"
languageCode = "en-us"
title = "A Tour of Dgraph"
theme="hugo-tutorials"
canonifyURLs = false

[[menu.main]]
  name = "GraphQL Introduction"
  url = "/graphqlintro/1/"
  identifier = "graphqlintro"
  weight = 1
[[menu.main]]
  name = "GraphQL Basic Features"
  url = "/graphqlbasic/1/"
  identifier = "graphqlbasic"
  weight = 2
[[menu.main]]
  name = "GraphQL Schema"
  url = "/graphqlschema/1/"
  identifier = "graphqlschema"
  weight = 3
[[menu.main]]
  name = "GraphQL Data and More Data"
  url = "/graphqlmoredata/1/"
  identifier = "graphqlmoredata"
  weight = 4
[[menu.main]]
  name = "GraphQL Search"
  url = "/graphqlsearch/1/"
  identifier = "graphqlsearch"
  weight = 5
[[menu.main]]
  name = "DQL Introduction"
  url = "/intro/1/"
  identifier = "intro"
  weight = 6
[[menu.main]]
  name = "DQL Basic Features"
  url = "/basic/1/"
  identifier = "basic"
  weight = 7
[[menu.main]]
  name = "DQL Schema"
  url = "/schema/1/"
  identifier = "schema"
  weight = 8
[[menu.main]]
  name = "DQL Data and More Data"
  url = "/moredata/1/"
  identifier = "moredata"
  weight = 9
[[menu.main]]
  name = "DQL Query Blocks and Variables"
  url = "/blocksvars/1/"
  identifier = "blocksvars"
  weight = 10
[[menu.main]]
  name = "DQL Search"
  url = "/search/1/"
  identifier = "search"
  weight = 11



[params]
  [params.menudesc]
    graphqlintro = "In this lesson you'll learn how to set up and run Dgraph Cloud for the GraphQL portion of this tour, and learn about graph databases."
    graphqlbasic = "Here you'll learn the basics of how to query graph data from Dgraph using GraphQL, and how to use and interpret the results."
    graphqlschema = "This lesson shows you how GraphQL schemas work inside Dgraph, and how to add, update and delete (or mutate) data."
    graphqlmoredata = "Now that you have some experience with Dgraph and GraphQL, this lesson shows you how to work with some larger datasets."
    graphqlsearch = "In this lesson, you'll learn about Dgraph's search features with GraphQL."
    intro = "In this lesson you'll learn how to set up and run Dgraph with Docker for the DQL portion of this tour, and also learn about graph databases."
    basic = "Here you'll learn the basics of how to query graph data from Dgraph and how to use and interpret the results."
    schema = "This lesson shows you how schemas work inside Dgraph, and how to add, update and delete (or mutate) data."
    moredata = "Now that you have some experience with Dgraph and DQL, this lesson shows you how to use the Live Loader tool to load large datasets.  You'll need this bigger dataset for the remaining sections of the tutorial."
    blocksvars = "This lesson shows you how to build more powerful queries with multiple query blocks and query variables."
    search = "In this lesson, you'll learn about Dgraph's search features with DQL."
